[package]
name = "nexo-v3"
version = "0.0.0"
description = "NEXO V3 IDE"
authors = ["NEXO"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
